apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hubenterntainmentapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hubenterntainmentapi
  template:
    metadata:
      labels:
        app: hubenterntainmentapi
    spec:
      containers:
      - name: hubenterntainmentapi-container
        image: hubenterntainmentapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 90